### ISSUE TITLE
The button component uses `transition: all` which could negatively impact performance

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#231]
Certain CSS properties leverage hardware (i.e., the CPU) when calculating animations (margin, padding, height, width). See:
https://blog.alexmaccaw.com/css-transitions#hardware-acceleration_2

When using `transition: all` these properties inevitably become animated. The good news is, the fix is simple. I would assume the properties of interest are `background` (maybe `background-color`?) and `color`, so just do this instead:

```css
.Button {
  ...
  transition: background .15s <easing>, color .15s <easing>;
  ...
}
```

Should be a pretty quick fix.
