### ISSUE TITLE
The <Tag/> component's content is not vertically centered

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#251]
![Screen Shot 2019-09-23 at 3 20 23 PM](https://user-images.githubusercontent.com/3613392/65455743-d8884700-de15-11e9-87bb-d385d0a1e2e3.png)

It looks like a few small adjustments would address it:

```css
.Content {
  display: inline-flex;
  align-items: center;
  // and get rid of vertical-align: middle <-- not doing anything outside of a table cell I don't think?
}
```
